### ISSUE TITLE
WorkFront WDC Only Pulls New Records when New Connection is Built

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt/workfront-wdc#9]
@tableau-mkt-bot commented on [Wed Sep 21 2016](https://github.com/tableau-mkt/marketing-etl/issues/59)

Title says it all.  Martin and Eric know the details.  This makes me cry.  Every night.

> **&lt;META&gt;**
> **Daniel Sullivan** submitted this issue on **Wed Sep 21 2016 22:26:00 GMT+0000 (UTC)**
> 
> **Problem / Request Statement:** null
> **Completion Criteria:** WDC pulls new data on refresh, not rebuild.
> **Url - Page Affected:** undefined
> **L.O.V:** 5
> **Requested Completion Date:** 2016-09-23
> **Original Ticket:** [Workfront](https://tableau.attask-ondemand.com/issue/view?ID=57e3091d00d3a94d81e0a8b560fa9a00)

**Comment by dsullivantableau** [comment]
You can close this.  We figured this out a long time ago.

**Comment by pvanoverbeek** [comment]
with pleasure
